//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyCompany("Ryan Conrad")]
[assembly: AssemblyCopyright("Copyright © Ryan Conrad 2007. All Rights Reserved.")]
[assembly: AssemblyDescription("collection of MSBuild tasks that can be used to perform actions to further automa" +
    "te the build process.")]
[assembly: AssemblyProduct("MSBuild Extended Tasks")]
[assembly: AssemblyTitle("MSBuild Extended Tasks")]
[assembly: AssemblyFileVersion("0.0.0.18")]
[assembly: AssemblyVersion("0.0.0.18")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]
[assembly: Guid("18060901-8fad-4bf8-a26f-d984a2fea521")]


